Add TypeScript definitions
posthtml/posthtml-match-helper pull request #7
Opened 2022-02-12 04:35 UTC by metonym

- add TypeScript definitions in `index.d.ts`
- adds `types` field in package.json

2022-02-16 19:24 UTC, phloe approved these changes
Looks good to me 🙂

2022-02-16 19:25 UTC, phloe commented
Maybe @voischev has an opinion?

2022-03-02 13:58 UTC, Scrum requested changes

2022-03-02 13:58 UTC, Scrum commented on index.d.ts
> +export default createMatcher;
there is already a part of types and declarations
https://github.com/posthtml/posthtml-parser/blob/0db4129ec0be89d3278149a4f8140a0c97facd6e/src/index.ts#L16-L28

2022-03-02 14:11 UTC, Scrum commented on index.d.ts
> +export default createMatcher;
> What's the requested change? To re-use the `NodeTag`?

yep



> One thing to note is that the [`Attributes` type](https://github.com/posthtml/posthtml-parser/blob/0db4129ec0be89d3278149a4f8140a0c97facd6e/src/index.ts#L17) doesn't have `RegExp` as a possible value.

you can always extend the base type

2022-03-02 14:25 UTC, metonym commented
@Scrum I noticed that `posthtml` does have a [`StringMatcher` type](https://github.com/posthtml/posthtml/blob/b3fd4ad2dbe8e9a8c0d4b6f9f0f9559a8ded1fc4/types/posthtml.d.ts#L6), which can be a string or `RegExp`.

I updated the typedefs to re-use types from `posthtml`.

Note that I didn't install `posthtml` as a dependency because it's already specified as a peer dependency.

I've also tested the types locally by copying/pasting them here: https://github.com/posthtml/posthtml-insert-at/blob/8ee129cc385a80159fbe843d49df73ba64543f3d/src/global.d.ts

2022-04-28 13:48 UTC, phloe approved these changes

2022-04-28 13:48 UTC, phloe commented
LGTM

2022-04-28 13:48 UTC, merged

2022-04-28 13:52 UTC, phloe commented
Now available on npm as posthtml-match-helper@1.0.2